### PR TITLE
Add backup for codeready PVs

### PR DESCRIPTION
**Pull request by sedroche**
Ticket: https://issues.jboss.org/browse/INTLY-1141

### CODE REVIEW

**Comment by sedroche** [comment]
@odra Can I rely on https://github.com/integr8ly/backup-container-image/pull/2 to provide encryption and storage?

**Comment by odra** [comment]
Yes

**Comment by odra** [comment]
@sedroche I just merged this one, feel free to rebase.

**Comment by odra** [comment]
:eyes:

**Comment by odra** [comment]
It this just archiving pgsql data? if so, shouldn't we use pgsql specialized tools + a generic script to handle pgsql backups?

**Comment by sedroche** [comment]
@odra There is also going to be SQL dump backups which will come under the postgres backup Job.

This is a backup of the PV. There are recovery methods which can be attempted with this data also:
https://www.postgresql.org/docs/9.1/backup-file.html

but more likely using:
https://www.postgresql.org/docs/9.1/continuous-archiving.html#BACKUP-BASE-BACKUP (Section 24.3.2 and Section 24.3.3)

I'm still trying to verify a backup using these methods.

**Pull request closed without merging**
