### PR TITLE
INTLY-1307: Fix tar command in resources backup

### PR DESCRIPTION
**Pull request by matskiv**
JIRA: https://issues.jboss.org/browse/INTLY-1307

Fixes `tar (child): Cannot connect to resources_15: resolve failed` error.
Solution explanation: https://unix.stackexchange.com/a/13381

### CODE REVIEW

**Comment by pb82** [comment]
:eyes:

**Comment by pb82** [comment]
@matskiv Would it also make sense to change the timestamp here to not use colons? https://github.com/integr8ly/backup-container-image/blob/master/image/tools/lib/component/resources.sh#L1

**Comment by matskiv** [comment]
@pb82 yes, that would be alternative solution. But I wanted to keep the same format across all components, thus - `--force-local`.

**Review by pb82 — APPROVED** [review]
Verified on RHPDS:
```
==> Component data dump completed
/tmp/intly/archives/resources_09:47:01.tar.gz
WARNING: resources_09:47:01.tar.gz: Owner username not known. Storing UID=1000000000 instead.
upload: '/tmp/intly/archives/resources_09:47:01.tar.gz' -> 's3://intly/backups/resources/resources/2019/03/15/resources_09:47:01.tar.gz'  [1 of 1]
 519678 of 519678   100% in    0s  1535.11 kB/s  done
==> Upload /tmp/intly/archives/resources_09:47:01.tar.gz completed
[2019/03/15] Backup completed
```

**Pull request merged**
